dependencies {
    // application layer
    implementation project(":user-service:application:member-application")
    // core layer
    implementation project(":core:kafka-event-core")
    // monglife-kafka
    implementation "com.github.monglife.monglife-module-common:monglife-module-common-kafka:${monglifeModuleCommonVersion}"
    // test
    testImplementation "org.springframework.kafka:spring-kafka-test"
}