plugins {
    id 'java-library'
    id 'org.springframework.boot' version '3.1.1'
    id 'io.spring.dependency-management' version '1.1.4'
}

bootJar {
    enabled(false)
}

allprojects {
    group = 'com.monglife.mongs'
    version = '2.1.0'

    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }

    tasks.register('copyPrivate', DefaultTask) {

        def configPath = '../../../configs/properties'
        def fullPath = project.path
        def pathSegments = fullPath.tokenize(':')

        if (pathSegments.size() > 1) {
            def parentModule = pathSegments[-2]
            def currentModule = pathSegments[-1]

            doLast {
                project.delete fileTree('src/main/resources') {
                    include('*.yml')
                    include('*.json')
                }
                project.delete fileTree('src/test/resources') {
                    include('*.yml')
                    include('*.json')
                }

                project.copy {
                    from(configPath + '/' + parentModule + '/' + currentModule + '/') {
                        include('*.yml')
                        include('*.json')
                    }
                    into('src/main/resources')
                }

                project.copy {
                    from(configPath + '/' + parentModule + '/' + currentModule + '/') {
                        include('*.yml')
                        include('*.json')
                        rename { fileName ->
                            if (fileName.endsWith(".yml") && fileName.contains("-")) {
                                return "application-test.yml"
                            }
                        }
                    }
                    into('src/test/resources')
                }
            }
        }
    }
}