buildscript {
    ext {
        springBootVersion                 = "3.1.1"
        springDependencyManagementVersion = "1.1.4"
        acuatorVersion                    = "3.2.1"
        lombokVersion                     = "1.18.30"
        monglifeCoreVersion               = "2.1.0"
        monglifeModuleCommonVersion       = "2.3.1"
        monglifeModuleMqttVersion         = "1.0.1"
        logstashVersion                   = "7.4"
        slf4jVersion                      = "2.0.7"
        jupiterVersion                    = "5.9.3"
        mockitoVersion                    = "4.8.1"
        assertjVersion                    = "3.24.2"
        awaitilityVersion                 = "4.2.0"
        testcontainersVersion             = "1.21.3"
    }
}

plugins {
    id "java-library"
    id "org.springframework.boot"        version "${springBootVersion}"
    id "io.spring.dependency-management" version "${springDependencyManagementVersion}"
}

bootJar {
    enabled(false)
}

subprojects {

    group = "com.monglife.mongs"
    version = "3.0.0"

    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    java {
        sourceCompatibility = JavaVersion.VERSION_17
    }

    tasks.register("copyPrivate", DefaultTask) {

        def configPath = "../../../configs/properties"
        def fullPath = project.path
        def pathSegments = fullPath.tokenize(":")

        if (pathSegments.size() > 1) {
            def parentModule = pathSegments[-2]
            def currentModule = pathSegments[-1]

            doLast {
                project.delete fileTree("src/main/resources") {
                    include("*.yml")
                    include("*.json")
                    include("*.xml")
                    include("*.sql")
                }

                project.delete fileTree("src/test/resources") {
                    include("*.yml")
                    include("*.json")
                }

                project.copy {
                    from(configPath + "/" + parentModule + "/" + currentModule + "/") {
                        include("*.yml")
                        include("*.json")
                        include("*.xml")
                        include("*.sql")
                    }
                    into("src/main/resources")
                }

                project.copy {
                    from(configPath + "/" + parentModule + "/" + currentModule + "/") {
                        include("*.yml")
                        include("*.json")
                        rename { fileName ->
                            if (fileName.endsWith(".yml")) {
                                return "application-test.yml"
                            }
                        }
                    }
                    into("src/test/resources")
                }
            }
        }
    }
}