rootProject.name = 'monglife-mongs'

include 'core'
include 'apps'
include 'apps:monglife-mongs-app-activity-api'
include 'apps:monglife-mongs-app-manager-api'
include 'apps:monglife-mongs-app-user-api'

include 'domains'
include 'domains:monglife-mongs-domain-match'
include 'domains:monglife-mongs-domain-member'
include 'domains:monglife-mongs-domain-mong'
include 'domains:monglife-mongs-domain-task'

include 'modules'
include 'modules:monglife-mongs-module-jpa'
include 'modules:monglife-mongs-module-mqtt'
include 'modules:monglife-mongs-module-security'
