rootProject.name = 'monglife-mongs'
//
//include 'apps'
//include 'apps:monglife-mongs-app-activity-api'
//include 'apps:monglife-mongs-app-manager-api'
//
//include 'clients'
//include 'clients:monglife-mongs-client-manager'
//include 'clients:monglife-mongs-client-user'
//
//include 'domains'
//include 'domains:monglife-mongs-domain-match'
//include 'domains:monglife-mongs-domain-mong'
//include 'domains:monglife-mongs-domain-task'

include 'bootstrap'
include 'bootstrap:character-bootstrap-api'
include 'bootstrap:user-bootstrap-api'

include 'adapter-in'
include 'adapter-in:battle-event-adapter-in'
include 'adapter-in:battle-web-adapter-in'
include 'adapter-in:device-web-adapter-in'
include 'adapter-in:device-event-adapter-in'
include 'adapter-in:member-web-adapter-in'
include 'adapter-in:member-event-adapter-in'
include 'adapter-in:mong-event-adapter-in'
include 'adapter-in:mong-web-adapter-in'

include 'application'
include 'application:battle-application'
include 'application:device-application'
include 'application:member-application'
include 'application:mong-application'

include 'domain'
include 'domain:device-domain'
include 'domain:member-domain'
include 'domain:mong-domain'
include 'domain:battle-domain'

include 'adapter-out'
include 'adapter-out:battle-persistence-adapter-out'
include 'adapter-out:battle-publish-adapter-out'
include 'adapter-out:device-persistence-adapter-out'
include 'adapter-out:device-publish-adapter-out'
include 'adapter-out:device-event-adapter-out'
include 'adapter-out:google-payment-adapter-out'
include 'adapter-out:member-event-adapter-out'
include 'adapter-out:member-persistence-adapter-out'
include 'adapter-out:member-publish-adapter-out'
include 'adapter-out:mong-persistence-adapter-out'
include 'adapter-out:mong-publish-adapter-out'
