dependencies {
    // adapter-in layer
    implementation project(":character-service:adapter-in:battle-schedule-adapter-in")
    implementation project(":character-service:adapter-in:battle-subscribe-adapter-in")
    implementation project(":character-service:adapter-in:battle-web-adapter-in")
    implementation project(":character-service:adapter-in:mong-event-adapter-in")
    implementation project(":character-service:adapter-in:mong-web-adapter-in")
    implementation project(":character-service:adapter-in:admin-web-adapter-in")

    // adapter-out layer
    implementation project(":character-service:adapter-out:battle-persistence-adapter-out")
    implementation project(":character-service:adapter-out:battle-publish-adapter-out")
    implementation project(":character-service:adapter-out:mong-event-adapter-out")
    implementation project(":character-service:adapter-out:mong-persistence-adapter-out")
    implementation project(":character-service:adapter-out:mong-publish-adapter-out")
    implementation project(":character-service:adapter-out:mong-schedule-adapter-out")

    // eureka
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client") {
        exclude group: "com.google.guava", module: "guava"
    }
    implementation "com.google.guava:guava:32.0.1-android"
}