dependencies {
    // adapter-in layer
    implementation project(":user-service:adapter-in:device-event-adapter-in")
    implementation project(":user-service:adapter-in:device-web-adapter-in")
    implementation project(":user-service:adapter-in:member-event-adapter-in")
    implementation project(":user-service:adapter-in:member-web-adapter-in")
    implementation project(":user-service:adapter-in:admin-web-adapter-in")

    // adapter-out layer
    implementation project(":user-service:adapter-out:device-cache-adapter-out")
    implementation project(":user-service:adapter-out:device-event-adapter-out")
    implementation project(":user-service:adapter-out:device-publish-adapter-out")
    implementation project(":user-service:adapter-out:google-payment-adapter-out")
    implementation project(":user-service:adapter-out:member-event-adapter-out")
    implementation project(":user-service:adapter-out:member-persistence-adapter-out")
    implementation project(":user-service:adapter-out:member-publish-adapter-out")

    // eureka
    implementation("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client") {
        exclude group: "com.google.guava", module: "guava"
    }
    implementation "com.google.guava:guava:32.0.1-android"
}