dependencies {
    // modules
    api project(':modules:monglife-mongs-module-jpa')
    implementation project(':modules:monglife-mongs-module-redis')
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/domains/monglife-mongs-domain-mong/'
        include 'application*.yml'
        into 'src/main/resources'
    }
}