dependencies {
    // modules
    api project(':modules:monglife-mongs-module-jpa')
    annotationProcessor project(':modules:monglife-mongs-module-jpa')       // For QueryDSL Generate QClass

    // redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/domains/monglife-mongs-domain-mong/'
        include 'application*.yml'
        into 'src/main/resources'
    }
}