dependencies {
    // application layer
    implementation project(':application:device-application')
    // monglife-kafka
    implementation 'com.github.monglife.monglife-module-common:monglife-module-common-kafka:1.0.11'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from('../../configs/adapter-out/device-event-adapter-out/') {
            include('application.yml')
            rename('application.yml', 'event-device.yml')
        }
        into('src/main/resources')
    }
    copy {
        from('../../configs/adapter-out/device-event-adapter-out/')
        include('application.yml')
        into('src/test/resources')
    }
}