package com.mongs.play.client.publisher.mong.code;

public enum PublishCode {
    NULL,
    REGISTER,           //MONG_CREATE,
    DELETE,             //MONG_DELETE,
    DEAD,               //MONG_DEAD,
    FEED,
    TRAINING,
    POOP_CLEAN,
    SLEEPING,
    STROKE,
    EVOLUTION_READY,    //MONG_EVOLUTION_READY,
    EVOLUTION,          //MONG_EVOLUTION,
    GRADUATION,         //MONG_GRADUATION,
    DECREASE_STATUS,
    INCREASE_STATUS,
    INCREASE_POOP_COUNT,
    EXCHANGE_PAY_POINT,

    CHARGE_STAR_POINT,
    INCREASE_STAR_POINT,
//        MONG_STROKE,
//        MONG_FEED,
//        MONG_SLEEPING,
//        MONG_POOP,
//        MONG_TRAINING,
//        MONG_SLEEP,
//        MONG_HEALTHY,
//        MONG_SATIETY,
//        MONG_STRENGTH,
//        MONG_WEIGHT,
//        MONG_STATE,
//        MONG_ATTENDANCE
}