dependencies {
    // monglife-feign
    implementation 'com.github.monglife.monglife-module-common:monglife-module-common-feign:1.0.5'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/clients/monglife-mongs-client-user/'
        include '*.yml'
        into 'src/main/resources'
    }
}