dependencies {
    api 'com.google.api-client:google-api-client:2.2.0'
    api 'com.google.apis:google-api-services-androidpublisher:v3-rev20231012-2.0.0'
    api 'com.google.auth:google-auth-library-oauth2-http:1.20.0'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/clients/monglife-mongs-client-google/'
        include 'application*.yml'
        into 'src/main/resources'
    }

    copy {
        from '../../configs/clients/monglife-mongs-client-google/'
        include '*.json'
        into 'src/main/resources'
    }
}