dependencies {
    // modules
    api project(':modules:monglife-mongs-module-feign')

    // Firebase Admin SDK
    api 'com.google.firebase:firebase-admin:9.2.0'
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/clients/monglife-mongs-client-fcm/'
        include 'application*.yml'
        into 'src/main/resources'
    }

    copy {
        from '../../configs/clients/monglife-mongs-client-fcm/'
        include '*.json'
        into 'src/main/resources'
    }
}