dependencies {
    // clients
    implementation project(':clients:monglife-mongs-client-user')

    // domains
    implementation project(':domains:monglife-mongs-domain-mong')
    implementation project(':domains:monglife-mongs-domain-task')

    // modules
    implementation project(':modules:monglife-mongs-module-security')
    implementation project(':modules:monglife-mongs-module-mqtt')
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/apps/monglife-mongs-app-manager-api/'
        include 'application*.yml'
        into 'src/main/resources'
    }
}