dependencies {
    // monglife-security
    implementation 'com.github.monglife.monglife-module-common:monglife-module-common-security:1.0.5'

    // monglife-mqtt
    implementation 'com.github.monglife:monglife-module-mqtt:1.0.0'

    // clients
    implementation project(':clients:monglife-mongs-client-manager')

    // domains
    implementation project(':domains:monglife-mongs-domain-match')
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/apps/monglife-mongs-app-activity-api/'
        include 'application*.yml'
        into 'src/main/resources'
    }
    copy {
        from '../../configs/common/'
        include 'common*.yml'
        into 'src/main/resources'
    }
}