plugins {
    id "java-library"
}

subprojects {
    apply plugin: "java-library"

    jar {
        enabled(true)
    }

    dependencies {
        // lombok
        compileOnly "org.projectlombok:lombok:${lombokVersion}"
        annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    }
}