dependencies {
    // domains
    implementation project(':domains:monglife-mongs-domain-member')

    // modules
    implementation project(':modules:monglife-mongs-module-security')
    implementation project(':modules:monglife-mongs-module-mqtt')
}

tasks.register('copyPrivate', Copy) {
    copy {
        from '../../configs/apps/monglife-mongs-app-player-api/'
        include 'application*.yml'
        into 'src/main/resources'
    }
}