dependencies {
}

tasks.register('copyPrivate', Copy) {
    copy {
        from('../../configs/application/mong-application/') {
            include('application.yml')
            rename('application.yml', 'application-mong.yml')
        }
        into('src/main/resources')
    }
    copy {
        from('../../configs/application/mong-application/')
        include('application.yml')
        into('src/test/resources')
    }
}