name: CD STAGE
on:
  push:
    branches:
      - stage
permissions:
  contents: read
  checks: write
  pull-requests: write
env:
  bootstrap-character-path: ./character-service/bootstrap/character-bootstrap-api
  bootstrap-user-path: ./user-service/bootstrap/user-bootstrap-api
  bootstrap-character: monglife-mongs-character-api
  bootstrap-user: monglife-mongs-user-api
  service-path: ~/service/mongs
  service-script: ~/service/mongs/run.sh
jobs:
  # 빌드 및 배포
  mongs-deploy:
    runs-on: ubuntu-latest
    environment: stage
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Bootstrap User API 빌드
      - name: Character Bootstrap API 모듈 빌드
        run: ./gradlew :character-service:bootstrap:character-bootstrap-api:build
      # Bootstrap User API 빌드
      - name: User Bootstrap API 모듈 빌드
        run: ./gradlew :user-service:bootstrap:user-bootstrap-api:build
      # 레포트 생성
      - name: 테스트 리포트 작성
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
      # 배포 파일 원격 복사
      - name: Character Bootstrap API 배포 파일 서버로 전송
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "${{ env.bootstrap-character-path }}/build/libs/*.jar"
          target: "${{ env.service-path }}/${{ env.bootstrap-character }}"
          strip_components: 5
          timeout: '120s'
      # 배포 스크립트 실행
      - name: Character Bootstrap API 서비스 실행
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sh ${{ env.service-script }} ${{ env.bootstrap-character }} ${{ env.service-path }}/${{ env.bootstrap-character }}
      # 배포 파일 원격 복사
      - name: User Bootstrap API 배포 파일 서버로 전송
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "${{ env.bootstrap-user-path }}/build/libs/*.jar"
          target: "${{ env.service-path }}/${{ env.bootstrap-user }}"
          strip_components: 5
          timeout: '120s'
      # 배포 스크립트 실행
      - name: User Bootstrap API 서비스 실행
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            sh ${{ env.service-script }} ${{ env.bootstrap-user }} ${{ env.service-path }}/${{ env.bootstrap-user }}