name: CI CHARACTER
on:
  pull_request:
    branches:
      - develop
permissions:
  contents: read
  checks: write
  pull-requests: write
jobs:
  # domain 모듈 단위 테스트
  domain-unit-test:
    name: Domain 모듈 단위 테스트
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Battle Domain 모듈 단위 테스트
      - name: Battle Domain 모듈 단위 테스트
        run: ./gradlew :character-service:domain:battle-domain:test
      # Mong Domain 모듈 단위 테스트
      - name: Mong Domain 모듈 단위 테스트
        run: ./gradlew :character-service:domain:mong-domain:test
      # 레포트 생성
      - name: 테스트 리포트 작성
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
  # application 모듈 단위 테스트
  application-unit-test:
    name: Application 모듈 단위 테스트
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Battle Application/Domain 모듈 단위 테스트
      - name: Battle Application/Domain 모듈 단위 테스트
        run: ./gradlew :character-service:application:battle-application:test
      # Mong Application/Domain 모듈 단위 테스트
      - name: Mong Application/Domain 모듈 단위 테스트
        run: ./gradlew :character-service:application:mong-application:test
      # 레포트 생성
      - name: 테스트 리포트 작성
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
  # adapter out 모듈 단위 테스트
  adapter-out-unit-test:
    name: Adapter out 모듈 단위 테스트
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Battle Persistence Adapter Out  모듈 단위 테스트
      - name: Battle Persistence Adapter Out 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-out:battle-persistence-adapter-out:test
      # Battle Publish Adapter Out  모듈 단위 테스트
      - name: Battle Publish Adapter Out 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-out:battle-publish-adapter-out:test
      # Mong Persistence Adapter Out 모듈 단위 테스트
      - name: Mong Persistence Adapter Out 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-out:mong-persistence-adapter-out:test
      # Mong Publish Adapter Out 모듈 단위 테스트
      - name: Mong Publish Adapter Out 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-out:mong-publish-adapter-out:test
      # Mong Schedule Adapter Out 모듈 단위 테스트
      - name: Mong Schedule Adapter Out 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-out:mong-schedule-adapter-out:test
      # 레포트 생성
      - name: 테스트 리포트 작성
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
  # adapter in 모듈 단위 테스트
  adapter-in-unit-test:
    name: Adapter in 모듈 단위 테스트
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Battle Subscribe Adapter In 모듈 단위 테스트
      - name: Battle Event Adapter In 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-in:battle-subscribe-adapter-in:test
      # Battle Web Adapter In 모듈 단위 테스트
      - name: Battle Web Adapter In 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-in:battle-web-adapter-in:test
      # Mong Event Adapter In 모듈 단위 테스트
      - name: Mong Event Adapter In 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-in:mong-event-adapter-in:test
      # Mong Web Adapter In 모듈 단위 테스트
      - name: Mong Web Adapter In 모듈 단위 테스트
        run: ./gradlew :character-service:adapter-in:mong-web-adapter-in:test
      # 레포트 생성
      - name: 테스트 리포트 작성
        uses: mikepenz/action-junit-report@v5
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
  # Character API 빌드 테스트
  bootstrap-build-test:
    name: Character API 빌드 테스트
    needs:
      - domain-unit-test
      - application-unit-test
      - adapter-out-unit-test
      - adapter-in-unit-test
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Bootstrap Character API 빌드
      - name: Character Bootstrap API 모듈 빌드
        run: ./gradlew :character-service:bootstrap:character-bootstrap-api:build -x test