name: CI DEVELOP
on:
  pull_request:
    branches: [ develop ]
jobs:
  # 각 모듈 별 단위 테스트
  unit-test:
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Device Application/Domain 모듈 단위 테스트
      - name: Device Application/Domain 모듈 단위 테스트
        run: ./gradlew :application:device-application:test
      # Member Application/Domain 모듈 단위 테스트
      - name: Member Application/Domain 모듈 단위 테스트
        run: ./gradlew :application:member-application:test
      # Device Event Adapter Out  모듈 단위 테스트
      - name: Device Event Adapter Out  모듈 단위 테스트
        run: ./gradlew :adapter-out:device-event-adapter-out:test
      # Device Persistence Adapter Out 모듈 단위 테스트
      - name: Device Persistence Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:device-persistence-adapter-out:test
      # Device Publish Adapter Out 모듈 단위 테스트
      - name: Device Publish Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:device-publish-adapter-out:test
      # Google Payment Adapter Out 모듈 단위 테스트
      - name: Google Payment Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:google-payment-adapter-out:test
      # Member Event Adapter Out 모듈 단위 테스트
      - name: Member Event Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:member-event-adapter-out:test
      # Member Persistence Adapter Out 모듈 단위 테스트
      - name: Member Persistence Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:member-persistence-adapter-out:test
      # Member Publish Adapter Out 모듈 단위 테스트
      - name: Member Publish Adapter Out 모듈 단위 테스트
        run: ./gradlew :adapter-out:member-publish-adapter-out:test
      # Device Event Adapter In 모듈 단위 테스트
      - name: Device Event Adapter In 모듈 단위 테스트
        run: ./gradlew :adapter-in:device-event-adapter-in:test
      # Device Web Adapter In 모듈 단위 테스트
      - name: Device Web Adapter In 모듈 단위 테스트
        run: ./gradlew :adapter-in:device-web-adapter-in:test
      # Member Event Adapter In 모듈 단위 테스트
      - name: Member Event Adapter In 모듈 단위 테스트
        run: ./gradlew :adapter-in:member-event-adapter-in:test
      # Member Web Adapter In 모듈 단위 테스트
      - name: Member Web Adapter In 모듈 단위 테스트
        run: ./gradlew :adapter-in:member-web-adapter-in:test
  # 빌드 테스트
  bootstrap-user-build-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      # 소스 로드
      - name: 소스 코드 로드
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          submodules: true
      # Java 환경 설정
      - name: JDK 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      # gradlew 권한 변경
      - name: Gradle 권한 부여
        run: chmod +x gradlew
      # 환경 설정 파일 로드
      - name: 환경 설정 파일 로드
        run: ./gradlew copyPrivate
      # Bootstrap User API 빌드
      - name: User Bootstrap API 모듈 빌드
        run: ./gradlew :bootstrap:user-bootstrap-api:build -x test
